### ISSUE TITLE
Shall JWSHeader implement toJSON and fromJSON type class?

### ISSUE THREAD

**Issue by haishengwu-okta** [frasertweedale/hs-jose#27]
https://hackage.haskell.org/package/jose-0.5.0.1/docs/Crypto-JOSE-JWS.html#t:JWSHeader

any particular reason it is not yet?

**Comment by frasertweedale** [comment]
It cannot be implemented because a JWSHeader serialises to *two* JSON objects: the unprotected header, and the protected header (which is then base64url-encoded).

Instead, there are instances ` HasParams a => FromJSON (Signature a)` and ` HasParams a => ToJSON (Signature a)` for working with signatures which are "one layer out", and which perform the proper processing of unprotected and protected header parameters.

What is your use case that requires aeson instances for the `JWSHeader` type directly?

**Comment by haishengwu-okta** [comment]
I'm trying to use the `JOSE.JWK.verify` which needs an `Alg` from the JWT header.

**Comment by haishengwu-okta** [comment]
I guess `JOSE.Compact.decodeCompact` is the right one I shall use. Thanks!

**Comment by frasertweedale** [comment]
Yes, JWT is a whole other issue... JWT is defined to use *only* the compact serialisation, so there's no aeson instances for JWT.
